#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------------------------------------------------------
    # EVERYTHING PAST THIS POINT IS OPTIONAL AND MOST LIKELY UNNECESSARY FOR NEW APPS
    #--------------------------------------------------------------------------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.app_name = "streamlit_app.py"
    args.repo = "https://github.com/streamlit/streamlit"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

